version: '3.7'

volumes:
    ibge-postgres:
        driver: 'local'

networks:
    ibge-net:
        driver: 'bridge'

services:
    db:
        container_name: ibge-db
        image: postgres:14.3
        volumes:
            - ibge-postgres:/var/lib/postgresql/data
        restart: always
        tty: true
        ports:
            - "3000:3306"
        environment:
            - POSTGRES_PASSWORD=${DB_PASS}
            - POSTGRES_USER=${DB_USER}
            - POSTGRES_DB=${DB_NAME}
            - TZ="America/Sao_Paulo"
        networks:
            - ibge-net

    webserver:
        container_name: ibge-nginx
        build:
            context: .
            dockerfile: docker/nginx/Dockerfile
        volumes:
            - ./:/app
            - ./docker/nginx/conf.d/app.conf:/etc/nginx/conf.d/default.conf
        ports:
            - "5000:80"
        restart: always
        depends_on:
            - db
            - app
        tty: true
        networks:
            - ibge-net

    app:
        container_name: ibge-php
        build:
            context: .
            dockerfile: docker/php/Dockerfile
        volumes:
            - ./:/app
        ports:
            - "9000"
        restart: always
        tty: true
        networks:
            - ibge-net

